<script src="<?= publicdir('vendor/jquery.min.js') ?>"></script>
<script src="<?= publicdir('vendor/jquery.validate.min.js') ?>"></script>
<script src="<?= publicdir('vendor/jquery.maskedinput.min.js') ?>"></script>
<script src="<?= publicdir('vendor/bootstrap.min.js') ?>"></script>
<script src="<?= publicdir('vendor/slick.min.js') ?>"></script>
<script src="<?= publicdir('js/main.js') ?>"></script>