<div class="footer">
	<div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-xs-6">
                <div class="phone">
                    <p>Тел:</p> <a href="tel:+79099234868"> +7 909 923-48-68</a>
                </div>
            </div>
            <div class="col-md-6 hidden-sm hidden-xs">
                <div class="copyrights">
                    <p>Торговая марка <a href="#">Panfil.</a> Все права защищены. 2016.</p>
                </div>
            </div>
            <div class="col-md-3 text-center col-xs-6">
                <div class="socials">
                    <ul>
                        <li>
                            <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>