
    <nav class="navbar navbar-default" role="navigation">
        <div class="row">
        <div class="navbar-header col-sm-2 col-xs-12">
            <a class="navbar-brand" href="#"><img src="<?= publicdir('images/panfil-logo.png') ?>"></a>
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#menu-collapse" aria-expanded="false" aria-controls="menu-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>

            </button>
        </div>
            <div class="col-sm-10">
        <div class="collapse navbar-collapse" id="menu-collapse">
                <ul class="nav navbar-nav row">
                    <li><a href="#"><span>О компании</span></a></li>
                    <li><a href="#"><span>Контакты</span></a></li>
                    <li><a href="#"><span>Wishlist</span></a></li>
                    <li><a href="#">
                            <span class="product-count">0</span>
                            <span>Корзина</span></a></li>
                    <li><a href="#">
                            <i style="background-image: url('/build/images/flag.png')" class="lang-icon"></i><span>en</span></a></li>
                </ul>
            </div>

        </div>
        </div>
    </nav>

