<div class="modal modal-subscribe fade" id="subscribe" tabindex="-1" role="dialog"
     aria-labelledby="subscribeLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
	            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
		            <span class="icon-bar"></span>
		            <span class="icon-bar"></span>
	            </button>
                <h4 class="modal-title" id="subscribeLabel">Подпишитесь на обновления, чтобы получать информацию
                                                            о новых моделях</h4>
            </div>
            <div class="modal-body">
                <input type="email" id="mail" placeholder="Электронная почта">
            </div>
            <div class="modal-footer">
                <button type="button" id="send" class="btn btn-default active">подписаться</button>
	            <button type="button" class="btn btn-default" data-dismiss="modal" aria-hidden="true">позже</button>
            </div>
        </div>
    </div>
</div>

<div class="modal modal-subscribe fade" id="subscribeOk" tabindex="-1" role="dialog"
     aria-labelledby="subscribeOkLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header modal-header--lg">
                <h4 class="modal-title" id="subscribeOkLabel">
	                спасибо за подписку! мы будем держать вас в курсе
	                всего самого интересного
                </h4>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-default active">закрыть</button>
            </div>
        </div>
    </div>
</div>
