<section class="content-about__item">
    <div class="company-logo"></div>
    <div class="company-info">
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut venenatis dictum auctor.Nullam
            sed eros sit amet diam suscipit interdum. Vestibulum pharetra nibh eget ipsum suscipit
            malesuada. Vestibulum facilisis cursus varius. Pellentesque ullamcorper auctor nisl,
            eu porttitor lectus. Vivamus at sollicitudin felis. Nulla aliquam, felis a fringilla aliquet,
            sem justo malesuada justo, vitae egestas lacus massa a felis. Proin faucibus purus vitae
            consectetur euismod.Lorem ipsum dolor sit amet,consectetur adipiscing elit. Cras fringilla leo ac
            orci rutrum, sit amet porttitor libero luctus. Nunc diam tortor, dapibus sit amet risus a,
            consectetur pulvinar diam. In vel orci dictum, porttitor metus sed, sollicitudin arcu.
        </p>
        <p>
            Morbi fermentum posuere euismod.Donec luctus elit quis ante imperdiet, non consectetur
            purus luctus.Sed eget porttitor augue. Integer quis lorem scelerisque,bibendum
            felis in, porta felis. Vestibulum gravida iaculis ex, eu luctus erat pulvinar ac.
            Nunc a lectus sed ligula tempus suscipit. Morbi sed nisi ultricies, feugiat nisi vitae, semper
            quam.Morbi auctor odio id ullamcorper fringilla.
        </p>
        <p>
            Aenean mi libero, tempus nec fermentum at, aliquet id justo. Integer accumsan lobortis lorem id
            mperdiet.Fusce egestas dolor vel lectus pretium, at lacinia nulla semper.
            Maecenas venenatis arcu vel iaculis maximus. Duis porta lacus sed quam vehicula rutrum.
            Duis finibus nulla nisl, vel convallis odio vehicula sit amet. Donec cursus eros lacus, aliquet facilisis ex
            congue vitae.Nulla porttitor lorem dui. Fusce quis iaculis erat. Mauris porta tempor justo,
            vitae aliquet metus fermentum sit amet. Praesent quis finibus nisl, eget pellentesque elit.
        </p>
    </div>
</section>