<section>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--buy">
                <img class="buy-image" src="<?= publicdir('images/buy-icon.png') ?>">
                <h3>28 900 руб</h3>
                <a href="#" class="btn btn-default active">Оформить все покупки</a>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-1.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-3.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-5.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-2.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-4.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--buy">
                <img class="buy-image" src="<?= publicdir('images/bascket-icon.png') ?>">
                <a href="#" class="btn btn-default">Продолжить покупки</a>
            </div>
        </div>

    </div>
</section>