<section class="checkout">
    <div class="container-fluid">
        <h2>Оформление заказа</h2>

            <form class="checkout__form" id="checkoutform" action="post">
                <div class="form-group row">
                    <div class="col-md-3">
                        <label for="phone" class="control-label">Телефон:</label>
                    </div>
                    <div class="col-md-6">
                        <input type="tel" class="form-control" id="phone" name="userPhone" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <label for="city" class="control-label">Населенный пункт:</label>
                    </div>
                    <div class="col-md-6">
                        <input type="text" class="form-control" id="city" required>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <label for="name" class="control-label">Имя:</label>
                    </div>
                    <div class="col-md-6">
                        <input type="text" class="form-control" id="name">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <label for="email" class=" control-label">Электронная почта:</label>
                    </div>
                    <div class="col-md-6">
                        <input type="email" class="form-control" id="email">
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <label for="comment" class="control-label">Комментарий:</label>
                    </div>
                    <div class="col-md-6">
                        <input type="text" class="form-control" id="comment">
	                    <div class="info-links">
		                    <a href="renouncement.html" target="_blank">Условия возврата товара</a> и <a href="return.html" target="_blank">отказа от выполнения договора</a>
	                    </div>
	                    <div class="requisites">
		                    ИП Панфиленко Марина Сергеевна. <br>
		                    Адрес: 121467, Россия, Москва, ул. Молодогвардейская 2 к 1<br>
		                    ИНН: 504905180488
	                    </div>
                    </div>
                </div>
                <h3>Итого: 24 500 руб</h3>
                <input class="btn btn-default active" type="submit" value="Купить">
            </form>

    </div>


</section>
<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="bascket bascket--product">
	                <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                    <div class="info">
                        <a href="#" class="delete-btn"></a>
                        <h3>9 800 руб</h3>
                        <a href="#" class="btn btn-default">Подробнее</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="bascket bascket--product">
	                <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                    <div class="info">
                        <a href="#" class="delete-btn"></a>
                        <h3>9 800 руб</h3>
                        <a href="#" class="btn btn-default">Подробнее</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="bascket bascket--product">
	                <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                    <div class="info">
                        <a href="#" class="delete-btn"></a>
                        <h3>9 800 руб</h3>
                        <a href="#" class="btn btn-default">Подробнее</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="bascket bascket--product">
	                <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                    <div class="info">
                        <a href="#" class="delete-btn"></a>
                        <h3>9 800 руб</h3>
                        <a href="#" class="btn btn-default">Подробнее</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="bascket bascket--product">
	                <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                    <div class="info">
                        <a href="#" class="delete-btn"></a>
                        <h3>9 800 руб</h3>
                        <a href="#" class="btn btn-default">Подробнее</a>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="bascket bascket--continue">
                    <img class="buy-image" src="<?= publicdir('images/bascket-icon.png') ?>">
                    <a href="#" class="btn btn-default">Продолжить покупки</a>
                </div>
            </div>

        </div>
    </div>
</section>