<section>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="clear-image">
                    <img src="<?= publicdir('images/buy-icon.png') ?>">
                </div>
                <h3>Пока пусто</h3>
                <a href="#" class="btn btn-default active">Начать покупки</a>
            </div>
        </div>
    </div>
</section>