<section class="contacts">
    <div class="info">
        <div class="info__address">
            <h1 class="h1">АДРЕС:</h1>
            <p>Левобережный переулок<br>
                д. 16, стр 2</p>
        </div>
        <div class="info__working">
            <p>
                Время работы: <span class="working-time">круглосуточно</span><br>
	            <span class="email">info@panfil-official.com</span><br>
                <span class="phone">Тел: <a href="tel:+7898378-97-97">+7 898 378-97-97</a></span>
            </p>
        </div>
    </div>
<div id="map"></div>
</section>