<section class="products">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                <div class="products__item">
                    <a href="#"><img src="<?= publicdir('images/dress-1.png') ?>"></a>
                    <div class="info">
                        <a href="#">
                            <i class="fa fa-heart-o active"></i>
                            <i class="fa fa-heart"></i>
                        </a>
                        <h3><span>9 800 руб</span></h3>
                        <a href="#" class="btn btn-default active">Купить</a>
                        <a href="#" class="btn btn-default">Отложить</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="products__item">
                    <a href="#"><img src="<?= publicdir('images/dress-2.png') ?>"></a>
                    <div class="info">
                        <a href="#">
                            <i class="fa fa-heart-o active"></i>
                            <i class="fa fa-heart"></i>
                        </a>
                        <h3><span>9 800 руб</span></h3>
                        <a href="#" class="btn btn-default active">Купить</a>
                        <a href="#" class="btn btn-default">Отложить</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="products__item  disabled">
                    <a href="#"><img src="<?= publicdir('images/dress-3.png') ?>"></a>
                    <div class="info">
                        <a href="#">
                            <i class="fa fa-heart-o active"></i>
                            <i class="fa fa-heart"></i>
                        </a>
                        <h3><span>9 800 руб</span></h3>
                        <a href="#" class="btn btn-default active">Купить</a>
                        <a href="#" class="btn btn-default">Отложить</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="products__item">
                    <a href="#"><img src="<?= publicdir('images/dress-4.png') ?>"></a>
                    <div class="info">
                        <a href="#">
                            <i class="fa fa-heart-o"></i>
                            <i class="fa fa-heart active"></i>
                        </a>
                        <h3><span>9 800 руб</span></h3>
                        <a href="#" class="btn btn-default active">Купить</a>
                        <a href="#" class="btn btn-default">Отложить</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="products__item">
                    <a href="#"><img src="<?= publicdir('images/dress-5.png') ?>"></a>
                    <div class="info">
                        <a href="#">
                            <i class="fa fa-heart-o active"></i>
                            <i class="fa fa-heart"></i>
                        </a>
                        <h3><span>9 800 руб</span></h3>
                        <a href="#" class="btn btn-default active">Купить</a>
                        <a href="#" class="btn btn-default">Отложить</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="products__item">
                    <a href="#"><img src="<?= publicdir('images/dress-6.png') ?>"></a>
                    <div class="info">
                        <a href="#">
                            <i class="fa fa-heart-o active"></i>
                            <i class="fa fa-heart"></i>
                        </a>
                        <h3><span>9 800 руб</span></h3>
                        <a href="#" class="btn btn-default active">Купить</a>
                        <a href="#" class="btn btn-default">Отложить</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>