<section>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
	            <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
	            <div class="basket-img" style="background-image: url('images/product-2-small.jpg')"></div>
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
	            <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
	            <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
	            <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="bascket bascket--product">
	            <div class="basket-img" style="background-image: url('images/product-1-small.jpg')"></div>
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
</section>