<section>
    <div class="row">
        <div class="col-md-3">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-1.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-2.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-3.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-4.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-1.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="bascket bascket--product">
                <img src="<?= publicdir('images/dress-2.png') ?>">
                <div class="info">
                    <a href="#" class="delete-btn"></a>
                    <h3>9 800 руб</h3>
                    <a href="#" class="btn btn-default">Подробнее</a>
                </div>
            </div>
        </div>
    </div>
</section>