<div class="actions-slider">
    <div class="item">
        <div class="action-image" style="background-image: url('/build/images/bag.png')"></div>
        <h2>Осенняя распродажа</h2>
        <p>
            Скидки до 70% на все
        </p>
        <a href="#" class="btn btn-default">Посмотреть коллекцию</a>
    </div>
    <div class="item">
        <div class="action-image" style="background-image: url('/build/images/bag.png')"></div>
        <h2>Осенняя распродажа</h2>
        <p>
            Скидки до 70% на все
        </p>
        <a href="#" class="btn btn-default">Посмотреть коллекцию</a>
    </div>
</div>