<div class="actions-slider">
    <div class="item" style="background-image: url('images/action-bg-1.jpg')">
        <h2>Новая коллекция весна-осень</h2>
        <p>
	        Открой новую коллекцию
        </p>
        <a href="#" class="btn btn-default">Посмотреть коллекцию</a>
    </div>
	<div class="item" style="background-image: url('images/action-bg-1.jpg')">
		<h2>Новая коллекция весна-осень</h2>
		<p>
			Открой новую коллекцию
		</p>
		<a href="#" class="btn btn-default">Посмотреть коллекцию</a>
	</div>
</div>