<div class="categories">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <div class="categories__item categories__item--big">
                    <h3 class="hidden-md">Платья</h3>
                    <a href="#"><img src="<?= publicdir('images/dress-1.png') ?>">
                        <h3 class="visible-md">Платья</h3>
                    </a>
                </div>
            </div>
            <div class="col-md-6 col-xs-12">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="categories__item categories__item--part">
                            <div class="row">
                                <div class="col-xs-6">
                                    <a href="#">
                                        <h3>Кошельки</h3>
                                    </a>
                                </div>
                                <div class="col-xs-6">
                                    <a href="#"><img src="<?= publicdir('images/purse.png') ?>"></a>
                                </div>
                            </div>

                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="categories__item categories__item--part">
                            <div class="row">
                                <div class="col-xs-6">
                                    <a href="#">
                                        <h3>Аксессуары</h3>
                                    </a>
                                </div>
                                <div class="col-xs-6">
                                    <a href="#"><img src="<?= publicdir('images/accessories.png') ?>"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3">
                <div class="categories__item categories__item--small">
                    <a href="#">
                        <div class="img-wrap">
                            <img src="<?= publicdir('images/jackets.png') ?>">
                        </div>

                        <h3>Куртки</h3>
                    </a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="categories__item categories__item--small">
                    <a href="#">
                        <div class="img-wrap">
                            <img src="<?= publicdir('images/blouses.png') ?>">
                        </div>
                        <h3>Блузы</h3>
                    </a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="categories__item categories__item--small">
                    <a href="#">
                        <div class="img-wrap">
                            <img src="<?= publicdir('images/skirts.png') ?>">
                        </div>
                        <h3>Юбки</h3>
                    </a>
                </div>
            </div>
            <div class="col-md-3">
                <div class="categories__item categories__item--small">
                    <a href="#">
                        <div class="img-wrap">
                            <img src="<?= publicdir('images/sweaters.png') ?>">
                        </div>
                        <h3>Кофты</h3>
                    </a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="categories__item categories__item--full">
                    <div class="row">
                        <div class="col-sm-6 col-xs-12 hidden-md">
                            <a href="#">
                                <h3>Популярные луки</h3>
                            </a>
                        </div>
                        <div class="col-sm-6 col-xs-12">
                            <a href="#"><img src="<?= publicdir('images/populars.png') ?>"></a>
                        </div>
                        <div class="col-md-6 visible-md">
                            <a href="#">
                                <h3>Популярные луки</h3>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>