<div class="categories">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-6 col-xs-12">
				<div class="categories__item categories__item--big">
					<a href="single_product.html" style="background-image: url('images/all-models.jpg')">
						<h3>Все модели</h3>
					</a>
				</div>
			</div>
			<div class="col-sm-6 col-xs-12">
				<div class="row">
					<div class="col-xs-12">
						<div class="categories__item categories__item--part">
							<a href="single_product.html" style="background-image: url('images/cloak.jpg')">
								<h3>Накидка</h3>
							</a>
						</div>
					</div>
					<div class="col-xs-12">
						<div class="categories__item categories__item--part">
							<a href="single_product.html" style="background-image: url('images/coat.jpg')">
								<h3>Пальто в клетку</h3>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 col-xs-6">
				<div class="categories__item categories__item--small">
					<a href="#" style="background-image: url('images/model-17.jpg')">
						<h3>Модель 17</h3>
					</a>
				</div>
			</div>
			<div class="col-md-3 col-xs-6">
				<div class="categories__item categories__item--small">
					<a href="#" style="background-image: url('images/model-92.jpg')">
						<h3>Модель 92</h3>
					</a>
				</div>
			</div>
			<div class="col-md-3 col-xs-6">
				<div class="categories__item categories__item--small">
					<a href="#" style="background-image: url('images/model-2.jpg')">
						<h3>Модель 2</h3>
					</a>
				</div>
			</div>
			<div class="col-md-3 col-xs-6">
				<div class="categories__item categories__item--small">
					<a href="#" style="background-image: url('images/model-23.jpg')">
						<h3>Модель 23</h3>
					</a>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<div class="categories__item categories__item--full">
					<a href="#" style="background-image: url('images/popular-look.jpg')">
						<h3>Популярные луки</h3>
					</a>
				</div>
			</div>
		</div>
	</div>
</div>